### ISSUE TITLE
Showing only for one time

### ISSUE THREAD

**Issue by babulpatel1309** [geftimov/android-player#11]
Like i added slide up animation for deletion of cart product.. First time its showing the animation but on the deletion of second product its not sliding up.. Just hide the view as it is. Please help me how to do it.

```
PropertyAction green = PropertyAction.newPropertyAction(custom_items).
                            translationY(custom_items.getChildAt(Integer.parseInt(delete.getTag().toString())).getHeight()).
                            alpha(1f).
                            duration(500).
                            build();

                    Player.init()
                            .animate(green)
                            .play();
```

Your library is seriously amazing.. And yah one more question is that if i want to translate my view from current position 0 to 1000 view alpha 1.0f to 0.0f then how can i achieve with your library.

Thank You.

**Comment by geftimov** [comment]
@babulpatel1309 You can do it simultaneously by calling multiple times animate(action) or one after the other by calling then().
For example 

``` java
animate(action).
then().
animate(otherAction)
```

That way they will wait for each other.

It is possible to animate everything with Player but don't do it.
The library is intended for post entering activity/fragment animations.

**Comment by babulpatel1309** [comment]
Sorry for late reply...I solved the issue by using Loop function... Thank You... :+1:  :) keep Smiling

**Comment by geftimov** [comment]
:) Nice.
