### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by thefirstcoder** [geftimov/android-player#14]
when I finish the activity,my application will stagnate for a period of time,afterwards the leak canary warn  a  message about memory leaked.I make sure that it caused by android-player.Can you help me?

details when I open it:

`In com.gongxun.centerdata:1.0.4:8.
- com.gongxun.centerdata.ui.MainUI has leaked:
- GC ROOT android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue
- references android.os.MessageQueue.mMessages
- references android.os.Message.next
- references android.os.Message.callback
- references com.eftimoff.androidplayer.Player$3.this$0 (anonymous class implements java.lang.Runnable)
- references com.eftimoff.androidplayer.Player.list
- references java.util.ArrayList.array
- references array java.lang.Object[].[0]
- references java.util.ArrayList.array
- references array java.lang.Object[].[0]
- references com.eftimoff.androidplayer.actions.property.PropertyAction.view
- references android.support.v7.widget.AppCompatImageView.mContext
- leaks com.gongxun.centerdata.ui.MainUI instance
- Reference Key: 7ff2f583-b6a4-4e73-bd8e-a5c03ad85f95
- Device: Xiaomi Xiaomi Mi-4c libra
- Android Version: 5.1.1 API: 22
- Durations: watch=5025ms, gc=186ms, heap dump=1727ms, analysis=7506ms`

**Comment by thefirstcoder** [comment]
oh,sorry,It's my negligence!
It will have a heavy repeat,if I won't set the count of the animation looping-"loop".

**Comment by geftimov** [comment]
@thefirstcoder 
Do you have this problem still?
I am investigating some memory leaks in another ticket so they could be indeed be a problem about it.

Thanks for reporting.

**Comment by thefirstcoder** [comment]
@geftimov 
It's ok! But I think you can make a warning about "loop" in README.
And another,android_player is so cool!
