### ISSUE TITLE
some method API need API 14 ,Can you support for API12 or lower

### ISSUE THREAD

**Issue by xiaomeixw** [geftimov/android-player#2]
Call requires API level 14 (current min is 12): android.view.ViewPropertyAnimator#setStartDelay ...
Call requires API level 14 (current min is 12): android.view.ViewPropertyAnimator#start

**Comment by pcqpcq** [comment]
maybe you need [NineOldAndroids](https://github.com/JakeWharton/NineOldAndroids/)

**Comment by xiaomeixw** [comment]
import com.nineoldandroids.animation.ObjectAnimator;
use NineOldAndroids can not fix the issue~~~

**Comment by geftimov** [comment]
@xiaomeixw 
Yes you are right.
I have tested the library for API 14 to API 21 without problems.
As i do not see that NineOldAndroids will help.
It is maybe better to make the library API min lvl to 14.
What do you think?

**Comment by pcqpcq** [comment]
it's not com.nineoldandroids.animation.ObjectAnimator, i think the [com.nineoldandroids.view.ViewPropertyAnimator](https://github.com/JakeWharton/NineOldAndroids/blob/master/library/src/com/nineoldandroids/view/ViewPropertyAnimator.java)  is what you want , you can check it out
@xiaomeixw

**Comment by xiaomeixw** [comment]
@geftimov my android project should support android 3.1 and + , so ......I wish if you have a way to support 2.3 and + It will be good ;

@pcqpcq there is no class to import com.nineoldandroids.view.ViewPropertyAnimator  
![qq 20150507151257](https://cloud.githubusercontent.com/assets/7067231/7510151/c2ed35dc-f4cb-11e4-95d9-9a1292344248.png)

**Comment by geftimov** [comment]
@xiaomeixw 
Ok i saw what do you mean.
I will work about this issue today and will keep you posted.

**Comment by xiaomeixw** [comment]
@geftimov Nice,Thanks for your hard work....

**Comment by pcqpcq** [comment]
@xiaomeixw 
you are going the wrong way...
it should be used like this:

``` java
ViewPropertyAnimator
    .animate(mYourView)
    .translationYBy(50)
    .setInterpolator(new LinearInterpolator())
    .start();
```

**Comment by geftimov** [comment]
@pcqpcq 
Exactly. I will make it as default implementation using NineOldDroids and that way
the library can support (ideally) from API 1.

**Comment by pcqpcq** [comment]
@geftimov nice! Thank you! :smile:

**Comment by xiaomeixw** [comment]
@pcqpcq  Perfect....I Rarely used ViewPropertyAnimator,Thanks for your remind;
@geftimov  use nineoldandroids can closed this issue;
Thanks,guys~~~

**Comment by xiaomeixw** [comment]
@pcqpcq  In Property Animation API,I usually use ValueAnimator、ObjectAnimator、propertyValuesHolder、AnimatorSet and so on,Rarely used ViewPropertyAnimator...
Thanks ...

**Comment by xiaomeixw** [comment]
@geftimov In PropertyAction.class , can change like this:

first:
@Override
public void animate(View view) {

```
ViewPropertyAnimator
       .animate(view)
       .translationX(toTranslationX).translationY(toTranslationY).scaleY(toScaleY).
           scaleX(toScaleX).alpha(toAlpha).rotation(toRotation).
            setDuration(getDuration()).setStartDelay(getDelay()).
                setInterpolator(getInterpolator()).start(); 
```

}

second:
every Class's TimeInterpolator should change to Interpolator...

I will test this code in android 2.3 phone and give you a feedback...If The code runs successfully , you can closed the issue#2...Thanks...

**Comment by geftimov** [comment]
@xiaomeixw 
Yea. Just today i have a lot of work and i will be available after noon to make and test this issue.

If you want you can make the issue and make a pull request.
That way you will be contributor to this open source project.

**Comment by xiaomeixw** [comment]
@geftimov  I am sorry ,I test code on my old 2.3+ phone ，it's crash;  
![1](https://cloud.githubusercontent.com/assets/7067231/7514822/c8c60f7e-f4f3-11e4-9ab4-91124b7d9e82.png)
![2](https://cloud.githubusercontent.com/assets/7067231/7514848/0c86b664-f4f4-11e4-993b-b7ea2867f9b5.png)

because view.setTranslationX only in 11 API,so need use nineoldandroids change like this：

![444335](https://cloud.githubusercontent.com/assets/7067231/7515208/83332bfa-f4f7-11e4-94f2-6d1ee842a9cb.png)

In end , That's OK run on 2.3 phone
Thanks @geftimov , this is a good and cool project~~~

**Comment by geftimov** [comment]
@xiaomeixw 

If you want make a pull request with the fixed functionality.
Make sure to test before submitting.

**Comment by geftimov** [comment]
@xiaomeixw 
compile 'com.eftimoff:androidplayer:1.0.1@aar'
should resolve your issues.

Please make it a test and write if everything works fine.

**Comment by yoavst** [comment]
Well I've tested my use cases and it worked on 2.3.

**Comment by geftimov** [comment]
Closing this one

**Comment by xiaomeixw** [comment]
@geftimov There is 6 hours of time difference between China and Bulgaria. So when your Answer my question  I was in sleep.... Thanks for your work, It's run successfully on 2.3 phone....That's great....

**Comment by geftimov** [comment]
From version 1.0.1
