### ISSUE TITLE
I want to add a feature that supports loop animation

### ISSUE THREAD

**Issue by markzhai** [geftimov/android-player#7]
I want to add a feature that supports loop animation, say like an icon becomes bigger and than smaller to its original size back and forth, like it is breathing.

But it's hard to add this function without adding something heavy to Player class(at least I need to know which List<BaseAction> needs how many times of loop, do you think if it's ok if I add this feature to Player, or I create a class inherite Player?

**Comment by geftimov** [comment]
If you want to make that change it would be alright.
Maybe it is better to add this feature to Player class.
Although i run into troubles when creating exiting animations (from Activity/Fragment).

How do you intent to implement this feature?
I am here if you need help.

**Comment by yoavst** [comment]
maybe you should implement this loop with callback for ending?

**Comment by geftimov** [comment]
@yoavst 
Who exactly do you mean?

**Comment by yoavst** [comment]
run animation one. On the `OnEnd` callback run animation two. On the `OnEnd` callback run the already defined animation one. LOOP.

Just add a Boolean to check if running is needed.

**Comment by geftimov** [comment]
@yoavst @markzhai 
Yea that can do the job done.

**Comment by markzhai** [comment]
Umm, maybe an integer is needed instead of boolean, which can allow user define loop times(0 or negative number for infinity) instead of only infinity loops. I'll try to pull this request in two days.

**Comment by geftimov** [comment]
Thanks for implementing the loop animation.
I have a question though.
@markzhai   @yoavst 
Is it better to release the https://jitpack.io/ instead in maven directly?

**Comment by yoavst** [comment]
Of course maven is better, but if you are short of time, or have no knowledge of maven (my case with my library) you can use jitpack.

**Comment by geftimov** [comment]
With a little delay. Uploaded to maven central.
v1.0.3
