### ISSUE TITLE
Fail to sync 'com.eftimoff:androidplayer:1.0.3@aar' from jCenter as well as MavenCentral

### ISSUE THREAD

**Issue by trietbui85** [geftimov/android-player#9]
Everytime I try to sync this library from jCenter as well as MavenCentral with 
`compile 'com.eftimoff:androidplayer:1.0.3@aar'`

Then I get this error:

> Error:(30, 13) Failed to resolve: com.eftimoff:androidplayer:1.0.3

**Comment by geftimov** [comment]
I will see what is the problem and keep you posted.

**Comment by geftimov** [comment]
Everything seems fine.
Here are the files in maven : http://repo1.maven.org/maven2/com/eftimoff/androidplayer/1.0.3/

**Comment by trietbui85** [comment]
Thanks for your support. It might belong to my Android Studio issue. I tried with other libraries and still get the same issue. Only libs which are added before are able to synced.

Let's close this issue :)

**Comment by geftimov** [comment]
Ok thanks.
